platform :ios, '9.0'
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/MLVision'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLModelInterpreter'
pod 'Firebase/MLVisionTextModel'

target 'MLKit-codelab' do
end